# Use this file to construct an environment
# for developing jgo from source.
#
#   mamba env create -f dev-environment.yml
#   conda activate jgo-dev
#
# In addition to the dependencies needed for using jgo, it includes tools
# for developer-related actions like running automated tests (pytest) and
# linting the code (black)
# If you want an environment without these tools, use environment.yml.
name: jgo-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Project dependencies
  - psutil
  # Developer tools
  - autopep8
  - build
  - black
  - flake8
  - pyflakes
  - pytest
  - pytest-cov
  # Project from source
  - pip
  - pip:
    - -e '.'
