[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "jgo"
version = "1.0.5.dev0"
authors = [{name = "SciJava team", email = "ctrueden@wisc.edu"}]
license = {text = "Unlicense"}
description = "Launch Java code from Python and the CLI, installation-free."
readme = "README.md"
urls = {Homepage = "https://github.com/scijava/jgo"}
requires-python = ">=3.7"
dependencies = ["psutil"]

[project.scripts]
jgo = "jgo:main"

[project.optional-dependencies]
# Ensure any changes to this list are also added to environment-test.yml!
dev = [
    "autopep8",
    "build",
    "black",
    "flake8",
    "isort",
    "pre-commit",
    "pyflakes",
    "pytest",
    "pytest-cov",
]

[tool.isort]
profile = "black"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
