[build-system]
requires = ["setuptools>=61.2", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[project]
name = "jgo"
version = "1.0.5.dev0"
authors = [{name = "SciJava team", email = "ctrueden@wisc.edu"}]
license = {text = "Unlicense"}
description = "Launch Java code from Python and the CLI, installation-free."
readme = "README.md"
urls = {Homepage = "https://github.com/scijava/jgo"}
requires-python = ">=3.6"
dependencies = ["psutil"]

[project.scripts]
jgo = "jgo:main"

[tool.setuptools]
packages = ["jgo"]
include-package-data = false

[tool.setuptools_scm]
